In [2]:
import sklearn

print(sklearn.__version__)

1.5.2

In [7]:
# Di seguito è riportato un esempio pratico di come definire, addestrare
#  e utilizzare un modello di classificazione utilizzando il dataset Iris.

# Importare le librerie necessarie
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Caricare il dataset Iris
iris = load_iris()
X = iris.data  # Caratteristiche (lunghezza e larghezza di sepali e petali)
y = iris.target  # Etichette (specie di Iris)

# Suddividere il dataset in set di training e test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Definire il modello: K-Nearest Neighbors Classifier
model = KNeighborsClassifier(n_neighbors=3)

# Addestrare il modello sui dati di training
model.fit(X_train, y_train)

# Fare predizioni sui dati di test
y_pred = model.predict(X_test)

# Valutare le prestazioni del modello
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuratezza del modello: {accuracy:.2f}")

Accuratezza del modello: 1.00

In [15]:
from sklearn.datasets import load_iris
import pandas as pd 

data = load_iris()
X = data.data
Y = data.target
df = pd.DataFrame(X, columns=data.feature_names)
df['Target'] = Y
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2